# Generated by Django 3.2.20 on 2023-08-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyollarKiyimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='yupka', max_length=100)),
                ('colour', models.CharField(default='qora', max_length=50)),
                ('price', models.IntegerField(default=100000000)),
            ],
        ),
        migrations.CreateModel(
            name='ErkaklarKiyimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' shim ', max_length=100)),
                ('colour', models.CharField(default='oq', max_length=50)),
            ],
        ),
    ]
